// Generated by ./build-aux/bin/authors.h-gen, do not edit by hand.

#define PACKAGE_SHORT_AUTHORS \


#define PACKAGE_AUTHORS \
  "Souleymane Meite <souleymane.meite@epita.fr>\n"                           \
  "David Xu <david.xu@epita.fr>\n"                                           \
  "Luca Laghouati <luca.laghouati@epita.fr>\n"                               \
  "Elias Dionyssopoulos <elias.dionyssopoulos@epita.fr>\n"
